apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    enablePrometheusMerge: true
    accessLogFile: /dev/stdout
    enableAutoMtls: true
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: LoadBalancer
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: http2
                port: 80
                targetPort: 8080
              - name: https
                port: 443
                targetPort: 8443
  values:
    global:
      proxy:
        accessLogEncoding: TEXT
        accessLogFile: /dev/stdout
      meshID: istio-mesh
      multiCluster:
        clusterName: istio-lab
